// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey)

function createMissingEnvProxy() {
  const message = "Supabase não configurado: defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY (ou VITE_SUPABASE_PUBLISHABLE_KEY) no ambiente do deploy.";
  return new Proxy({}, {
    get() {
      throw new Error(message);
    }
  }) as any;
}

// Wrapper para adicionar timeout às requisições fetch
const fetchWithTimeout = (timeout: number) => {
  return async (input: RequestInfo | URL, init?: RequestInit) => {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeout);

    try {
      const response = await fetch(input, {
        ...init,
        signal: controller.signal,
      });
      clearTimeout(timeoutId);
      return response;
    } catch (error: any) {
      clearTimeout(timeoutId);
      if (error.name === 'AbortError') {
        throw new Error(`Request timeout after ${timeout}ms`);
      }
      throw error;
    }
  };
};

export const supabase = (!supabaseUrl || !supabaseAnonKey)
  ? createMissingEnvProxy()
  : createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      // Timeout de 30 segundos para prevenir requisições travadas
      fetch: fetchWithTimeout(30000),
    },
    db: {
      schema: 'public',
    },
    // Configuração de realtime para otimizar conexões WebSocket
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  })