// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
export const isSupabaseConfigured = Boolean(supabaseUrl && supabaseAnonKey)

function createMissingEnvProxy() {
  const message = "Supabase não configurado: defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY (ou VITE_SUPABASE_PUBLISHABLE_KEY) no ambiente do deploy.";
  return new Proxy({}, {
    get() {
      throw new Error(message);
    }
  }) as any;
}

export const supabase = (!supabaseUrl || !supabaseAnonKey)
  ? createMissingEnvProxy()
  : createClient(supabaseUrl, supabaseAnonKey)